project:
  type: website
  output-dir: docs

website:
  title: "Andrea De Angelis"
  description: "Political Scientist | Computational Social Science"
  favicon: files/icon.png
  
  # Enhances how links look when shared on LinkedIn/Twitter
  open-graph: true
  twitter-card: true

  navbar:
    background: "#FDFBF7" # Cream
    foreground: "#22333B" # Dark Blue
    logo: files/icon.png
    title: "Andrea De Angelis"
    search: true
    collapse: true # Better mobile experience
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Supervision"
        href: supervision.qmd
      - text: "CV"
        href: "files/CV_DeAngelis.pdf"
      - text: "News"
        href: news.qmd
        target: _blank


  page-footer:
    border: true
    left: "Â© 2025 Andrea De Angelis"
    center: "[Department of Social and Political Sciences](https://www.unimi.it/en), University of Milan"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    site-map: true
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    include-in-header:
      - text: |
          <meta name="google-site-verification" content="Zz-qxF05cWb5JpnpOHUZKTpkwn8oMOHmtL8IBWzTBBc" />
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    toc: false
    mainfont: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif"